version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  frontend:
    build: .
    container_name: vue_app
    ports:
      - "5173:80"

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: lekha_bill_app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"